---
- hosts: localhost
  tasks:
    - name: Install packages
      apt:
        name:
        - git
        - fail2ban
        - ufw
        - nginx
        - php7.2-cli
        - php7.2-curl
        - php7.2-fpm
        - php7.2-mysql
        - php7.2-bcmath
        - php7.2-mbstring
        - php7.2-tokenizer
        - php7.2-xml
        - php7.2-json
        - mariadb-server
        - python-mysqldb
        update_cache: yes
        state: present
        
    - name: Create a webmaster user
      user:
        name: webmaster
        password: $6$TDArDjR6$BQc8.pBdtwzqvQPTDyVXu5FxU/4sLY0a/b5jv2RSQWDgTlcPGlogrmI.AOPgT1kXWTyKpvUklAJwq4.5P8wWP.
        shell: /bin/bash
        state: present
        
    - name: Create MySQL database
      mysql_db:
        name: app_db
        state: present
        
    - name: Create MySQL user
      mysql_user:
        name: app_user
        state: present
        password: app_user_password
        priv: 'app_db.*:ALL'
        
    - name: Get Composer installer signature.
      uri:
        url: https://composer.github.io/installer.sig
        return_content: true
      register: composer_installer_signature
    - name: Download Composer installer.
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755
        checksum: "sha384:{{ composer_installer_signature.content }}"
    - name: Run Composer installer.
      command: >
        php composer-installer.php
        chdir=/tmp
    - name: Move Composer into globally-accessible location
      command: >
        mv /tmp/composer.phar /usr/local/bin/composer
        creates=/usr/local/bin/composer
